/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ChorusCharts {
  album_art_md5: string | null;
  artist: string;
  artist_normalized: string | null;
  charter: string;
  charter_normalized: string | null;
  diff_bass: number | null;
  diff_drums: number | null;
  diff_drums_real: number | null;
  diff_guitar: number | null;
  diff_keys: number | null;
  group_id: number;
  has_video_background: number;
  md5: string;
  modified_time: string;
  name: string;
  name_normalized: string | null;
  song_length: number | null;
}

export interface ChorusMetadata {
  key: string | null;
  updated_at: Generated<string>;
  value: string;
}

export interface ChorusScanSessions {
  completed_at: string | null;
  id: Generated<number | null>;
  last_chart_id: number | null;
  scan_since_time: string;
  started_at: string;
  status: string;
}

export interface LocalCharts {
  artist: string;
  artist_normalized: string | null;
  charter: string;
  charter_normalized: string | null;
  data: string;
  id: Generated<number | null>;
  modified_time: string;
  song: string;
  song_normalized: string | null;
  updated_at: string;
}

export interface SpotifyAlbums {
  artist_name: string;
  id: string;
  name: string;
  total_tracks: Generated<number>;
  updated_at: string;
}

export interface SpotifyAlbumTracks {
  album_id: string;
  track_id: string;
  updated_at: string;
}

export interface SpotifyPlaylists {
  collaborative: Generated<number>;
  id: string;
  name: string;
  owner_display_name: string;
  owner_external_url: string;
  snapshot_id: string;
  total_tracks: Generated<number>;
  updated_at: string;
}

export interface SpotifyPlaylistTracks {
  playlist_id: string;
  track_id: string;
}

export interface SpotifyTracks {
  artist: string;
  artist_normalized: string | null;
  id: string;
  name: string;
  name_normalized: string | null;
  updated_at: string;
}

export interface SpotifyTrackChartMatches {
  spotify_id: string;
  chart_md5: string;
  matched_at: number;
}

export interface SpotifyHistory {
  artist: string;
  artist_normalized: string;
  name: string;
  name_normalized: string;
  play_count: number;
}

export interface DB {
  chorus_charts: ChorusCharts;
  chorus_metadata: ChorusMetadata;
  chorus_scan_sessions: ChorusScanSessions;
  local_charts: LocalCharts;
  spotify_album_tracks: SpotifyAlbumTracks;
  spotify_albums: SpotifyAlbums;
  spotify_history: SpotifyHistory;
  spotify_playlist_tracks: SpotifyPlaylistTracks;
  spotify_playlists: SpotifyPlaylists;
  spotify_track_chart_matches: SpotifyTrackChartMatches;
  spotify_tracks: SpotifyTracks;
}
