/**
 * "Ours" v5 parity on 3 synthetic edge-case charts (empty groove measures, a
 * mid-song time-signature change, and a song with no kick/snare at all —
 * `aug_dist_backbone_ms`'s 5000ms sentinel path) from the unrelated
 * `drum-reducer-reference` project's `data/fixtures/charts/` — see
 * `__fixtures__/MANIFEST.md`'s "`drum-reducer-reference` cross-check" note
 * for how that project relates to this one (same trained `591ab4a` model,
 * byte-identical `.bin` files, but an independently-designed decode with a
 * few different tie-break conventions).
 *
 * These 3 charts are fully synthetic (generic section names, no song/artist
 * identity — safe to commit, unlike that project's 99 real-song fixtures,
 * which this repo does not carry per the anonymization policy). They aren't
 * in `.mid`/`.ini` form (no scan-chart resolution/tick — the reference
 * project's own schema is already-parsed `{tempos, timeSignatures, sections,
 * era, difficulties.expert.notes}` JSON, see `SPEC.md` §7), so this test
 * calls `featurizeSong`/`reduceOurs` directly instead of going through
 * `readChart`/the adapter, and asserts on `(ms, lane)` (there's no native
 * tick to assert on) — the same basis the reference project's own
 * `parity_fixture.json` uses.
 *
 * Expected output was generated by the REAL production script
 * (`train_pinned_591ab4a.py`/`consistency_metric.py`, this project's actual
 * ground truth — NOT blindly trusted from the reference project's own
 * output, since a 2026-07-22 investigation found their decode's tie-breaks
 * can genuinely differ; see `gen_edge_case_expected.py`'s docstring). All 3
 * happen to agree with the reference project's own expected output too
 * (confirmed via a one-time 102-song diagnostic — 0.004% note-level
 * divergence overall, none on these 3 edge cases), so there's no ambiguity
 * about which is "right" here.
 */

import {readFileSync} from 'fs';
import {join} from 'path';
import {reduceOurs} from '../reduce';
import {parseSurviveBin, parseRelaneBin} from '../model';
import type {OursModels, RelaneModel, SurviveModel, Tier} from '../model';
import type {OursNoteInput, OursSongInput} from '../featurize';

const FIXTURES_DIR = join(
  __dirname,
  '..',
  '__fixtures__',
  'referenceEdgeCases',
);
const MODELS_DIR = join(
  __dirname,
  '..',
  '..',
  '..',
  '..',
  'public',
  'models',
  'drum-difficulty',
  'v5',
);
const NAMES = [
  'edge-empty-groove-measures',
  'edge-midsong-ts-change',
  'edge-no-backbone',
];
const TIERS: Tier[] = ['hard', 'medium', 'easy'];

interface ManifestJson {
  family_nms_gaps_ms: Record<Tier, number | null>;
  survive_threshold: number;
  families: {cymbal: string[]; tom: string[]};
}

/** Same model-loading approach as `parity.test.ts` — see that file for why
 * `Buffer` needs copying into a fresh `ArrayBuffer` before `model.ts`'s
 * binary parsers can accept it. */
function loadModels(): OursModels {
  const manifest = JSON.parse(
    readFileSync(join(MODELS_DIR, 'manifest.json'), 'utf8'),
  ) as ManifestJson;
  const readBin = (name: string): ArrayBuffer => {
    const buf = readFileSync(join(MODELS_DIR, name));
    const out = new ArrayBuffer(buf.byteLength);
    new Uint8Array(out).set(buf);
    return out;
  };
  const survive = {} as Record<Tier, SurviveModel>;
  const relane = {} as Record<Tier, {cymbal: RelaneModel; tom: RelaneModel}>;
  for (const tier of TIERS) {
    const s = parseSurviveBin(readBin(`survive_${tier}.bin`));
    s.threshold = manifest.survive_threshold;
    survive[tier] = s;
    relane[tier] = {
      cymbal: parseRelaneBin(
        readBin(`relane_cymbal_${tier}.bin`),
        manifest.families.cymbal,
      ),
      tom: parseRelaneBin(
        readBin(`relane_tom_${tier}.bin`),
        manifest.families.tom,
      ),
    };
  }
  return {survive, relane, familyNmsGapsMs: manifest.family_nms_gaps_ms};
}

interface RefChartNoteEntry {
  instrument: string;
  ghost?: boolean;
  accent?: boolean;
  flam?: boolean;
}
interface RefChart {
  tempos: {ms: number; bpm: number}[];
  timeSignatures: {ms: number; numerator: number; denominator: number}[];
  sections: {ms: number; name: string}[];
  era: string;
  difficulties: {expert: {notes: [number, RefChartNoteEntry[]][]}};
}

/** `SPEC.md` §7's already-grouped chart JSON -> {@link OursSongInput}. There's
 * no native chart resolution/tick here (unlike a real `.mid`), so each
 * distinct `ms` bucket gets its own synthetic `tick` (its index in the
 * already-ms-ordered `notes` array) purely so `featurizeSong`'s chord
 * grouping (which keys on `tick`, not `ms`) sees one chord per bucket — the
 * assertion below is on `(ms, lane)`, so the synthetic tick's actual value
 * never matters. */
function toOursSongInput(chart: RefChart): OursSongInput {
  const notes: OursNoteInput[] = [];
  chart.difficulties.expert.notes.forEach(([ms, entries], tick) => {
    for (const e of entries) {
      notes.push({
        tick,
        ms,
        lane: e.instrument as OursNoteInput['lane'],
        ghost: e.ghost ?? false,
        accent: e.accent ?? false,
        flam: e.flam ?? false,
      });
    }
  });
  return {
    notes,
    tempos: chart.tempos,
    timeSignatures: chart.timeSignatures,
    sections: chart.sections,
    resolution: 480,
  };
}

interface ExpectedNote {
  ms: number;
  lane: string;
}

const canon = (n: {msTime: number; lane: string}) =>
  `${n.msTime.toFixed(3)}|${n.lane}`;
const canonExpected = (n: ExpectedNote) => `${n.ms.toFixed(3)}|${n.lane}`;

describe('Ours v5 — drum-reducer-reference synthetic edge cases', () => {
  const models = loadModels();

  for (const name of NAMES) {
    test(name, () => {
      const chart: RefChart = JSON.parse(
        readFileSync(join(FIXTURES_DIR, `${name}.json`), 'utf8'),
      );
      const expected: Record<Tier, ExpectedNote[]> = JSON.parse(
        readFileSync(join(FIXTURES_DIR, `${name}.expected.json`), 'utf8'),
      );

      const tiers = reduceOurs(toOursSongInput(chart), models);

      for (const tier of TIERS) {
        const got = tiers[tier].map(canon).sort();
        const want = expected[tier].map(canonExpected).sort();
        expect(got).toEqual(want);
      }
    });
  }
});
