/**
 * An invented test chart, generated by code: a steady drum groove and a
 * guitar riff with a few sung syllables, so the highway, its karaoke line
 * and the checks built on them can run on no song material at all. No
 * imports: Node scripts write it to disk (a chart folder for the sync check)
 * and compositions parse it in memory (the app's
 * `readChartForEditing(testChartFiles())`).
 *
 * The pattern, per 4/4 bar (eighths e = 0..7): hi-hat cymbal on every eighth
 * (a crash instead on the downbeat of every fourth bar), kick on e 0 and 4
 * (and 5 in odd bars), snare on e 2 and 6, a tom on e 7 closing every fourth
 * bar. The guitar plays an eighth-note riff over a sustained chord on each
 * even bar's downbeat, and an open note closes every other bar.
 */

export interface TestChartOptions {
  /** Length in bars (default 16). */
  bars?: number;
  /** Tempo (default 120: a beat is half a second, a bar two seconds). */
  bpm?: number;
  /** Sung syllables for the karaoke line (default true). */
  lyrics?: boolean;
}

/** Ticks per quarter note. */
export const TEST_CHART_RESOLUTION = 192;

const EIGHTH = TEST_CHART_RESOLUTION / 2;
const BAR = TEST_CHART_RESOLUTION * 4;

/** .chart drum note numbers (four-lane pro drums). */
const DRUM = {kick: 0, red: 1, yellow: 2, blue: 3, green: 4} as const;
const CYMBAL = {yellow: 66, blue: 67, green: 68} as const;

/**
 * A lone snare the checks can look for: bar 2's second backbeat (bar 2,
 * beat 2 counting from 0, eighth 2). No other red note shares its tick.
 */
export const TEST_PROBE_NOTE = {
  instrument: 'drums',
  lane: 'red',
  tick: 2 * BAR + 2 * EIGHTH,
} as const;

/** Song seconds of a tick in the test chart. */
export const testChartSeconds = (tick: number, bpm = 120): number =>
  (tick / TEST_CHART_RESOLUTION) * (60 / bpm);

const SYLLABLES = ['high', 'way', 'test', 'line', 'one', 'two', 'three'];

const drumLines = (bars: number): string[] => {
  const lines: string[] = [];
  const note = (tick: number, n: number) => lines.push(`  ${tick} = N ${n} 0`);
  for (let bar = 0; bar < bars; bar++) {
    for (let e = 0; e < 8; e++) {
      const tick = bar * BAR + e * EIGHTH;
      const crash = e === 0 && bar % 4 === 0;
      if (e === 0 || e === 4 || (e === 5 && bar % 2 === 1))
        note(tick, DRUM.kick);
      if (e === 2 || e === 6) note(tick, DRUM.red);
      if (e === 7 && bar % 4 === 3) note(tick, DRUM.blue);
      else if (crash) {
        note(tick, DRUM.green);
        note(tick, CYMBAL.green);
      } else {
        note(tick, DRUM.yellow);
        note(tick, CYMBAL.yellow);
      }
    }
  }
  return lines;
};

const RIFF = [0, 1, 2, 1, 3, 2, 1, 0];

const guitarLines = (bars: number): string[] => {
  const lines: string[] = [];
  for (let bar = 0; bar < bars; bar++) {
    const base = bar * BAR;
    if (bar % 2 === 0) {
      lines.push(`  ${base} = N 0 ${TEST_CHART_RESOLUTION}`);
      lines.push(`  ${base} = N 2 ${TEST_CHART_RESOLUTION}`);
    }
    for (let e = bar % 2 === 0 ? 2 : 0; e < 8; e++) {
      const tick = base + e * EIGHTH;
      if (e === 7 && bar % 2 === 1) lines.push(`  ${tick} = N 7 0`);
      else lines.push(`  ${tick} = N ${RIFF[e]} 0`);
    }
  }
  return lines;
};

/** A phrase every two bars from bar 1: one syllable per beat, closing before the next phrase. */
const lyricLines = (bars: number): string[] => {
  const lines: string[] = [];
  let word = 0;
  for (let bar = 1; bar + 1 < bars; bar += 2) {
    const start = bar * BAR;
    lines.push(`  ${start} = E "phrase_start"`);
    for (let beat = 0; beat < 4; beat++) {
      const text = SYLLABLES[word++ % SYLLABLES.length];
      lines.push(
        `  ${start + beat * TEST_CHART_RESOLUTION} = E "lyric ${text}"`,
      );
    }
    lines.push(`  ${start + BAR + 2 * TEST_CHART_RESOLUTION} = E "phrase_end"`);
  }
  return lines;
};

const section = (name: string, lines: readonly string[]): string =>
  `[${name}]\n{\n${lines.join('\n')}\n}`;

/** The chart as .chart text. */
export const testChartText = ({
  bars = 16,
  bpm = 120,
  lyrics = true,
}: TestChartOptions = {}): string =>
  [
    section('Song', [
      `  Resolution = ${TEST_CHART_RESOLUTION}`,
      '  Offset = 0',
    ]),
    section('SyncTrack', ['  0 = TS 4', `  0 = B ${Math.round(bpm * 1000)}`]),
    section('Events', lyrics ? lyricLines(bars) : []),
    section('ExpertSingle', guitarLines(bars)),
    section('ExpertDrums', drumLines(bars)),
  ].join('\n') + '\n';

/** The chart's song.ini: an invented title, pro drums, and its length. */
export const testSongIni = ({
  bars = 16,
  bpm = 120,
}: TestChartOptions = {}): string =>
  [
    '[song]',
    'name = Highway test pattern',
    'pro_drums = True',
    `song_length = ${Math.round(bars * 4 * (60 / bpm) * 1000)}`,
    '',
  ].join('\n');

/** notes.chart and song.ini as chart files (scan-chart's `File` shape). */
export const testChartFiles = (
  options: TestChartOptions = {},
): {fileName: string; data: Uint8Array}[] => {
  const encoder = new TextEncoder();
  return [
    {fileName: 'notes.chart', data: encoder.encode(testChartText(options))},
    {fileName: 'song.ini', data: encoder.encode(testSongIni(options))},
  ];
};
